SELECT
    CASE
        WHEN START_DATE LIKE '2022-08%' THEN 8
        WHEN START_DATE LIKE '2022-09%' THEN 9
        WHEN START_DATE LIKE '2022-10%' THEN 10
    END AS MONTH,
    CAR_ID,
    COUNT(*) AS RECORDS
FROM
    CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
    GROUP BY CAR_ID
    HAVING COUNT(CAR_ID) >= 5
    ) AND START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
GROUP BY
    MONTH, CAR_ID
HAVING
    RECORDS != 0
ORDER BY
    MONTH, CAR_ID DESC;