SELECT
    CAR_ID, ROUND(AVG_DUR, 1) AS AVERAGE_DURATION
FROM
    CAR_RENTAL_COMPANY_RENTAL_HISTORY
INNER JOIN (
    SELECT CAR_ID, AVG(DATEDIFF(END_DATE, START_DATE) + 1) AS AVG_DUR
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    GROUP BY CAR_ID
    HAVING AVG_DUR >= 7
) A
    USING (CAR_ID)
GROUP BY
    CAR_ID
ORDER BY
    AVERAGE_DURATION DESC, CAR_ID DESC;